controllers/category_controller.py
from flask import redirect, flash, request, url_for, Blueprint
from flask_login import login_required, current_user
from decorators import admin_required
from logmanagerconfig import login_manager

from models.user_model import User
from models.book_model import Book

from models.category_model  import Category
from views import category_view
from forms.form_categories import CreateForm, EditForm

from database import db

category_bp = Blueprint('category', __name__, url_prefix='/categories')

#login_manager
@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(user_id) 

@category_bp.route("/")
#@admin_required
def index():
    categories = Category.get_all()
    return category_view.list(categories=categories)

@category_bp.route("/admin/create", methods=['POST','GET'])
@admin_required #if not flash + redirect to run.index 
def create():
    form = CreateForm()
    
    if 'cancel' in request.form:
        return redirect(url_for('category.index'))
    
    if form.validate_on_submit():
        name =  form.name.data
        description = form.description.data
        is_active = form.is_active.data
        
        category = Category(name, description, is_active)
        try:
            category.save() # commit the creation
            flash("Successfully Added","success")
            return redirect(url_for('category.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot Create, Error:{e}", "danger")
    return category_view.create(form=form)
         
@category_bp.route("/admin/edit/<int:id>", methods= ['POST','GET'])
@admin_required
def edit(id):
    category = Category.get_by_id(id)
    form = EditForm(obj=category)
    
    if 'cancel' in request.form:
        return redirect(url_for('category.index'))
    
    if form.validate_on_submit():
        form.populate_obj(category)        
        try:
            db.session.commit()
            flash("Succesfully Updated", "success")
            return redirect(url_for('category.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot update, Error:{e}", "danger")
    return category_view.edit(form=form, category=category)

@category_bp.route("/admin/delete/<int:id>", methods=['POST','GET'])
@admin_required
def delete(id):
    category = Category.get_by_id(id)
    book_count = Book.get_by_category_id_count(id)   
    if book_count > 0:
        flash(f"No se puede eliminar la categoria '{category.name}' porque tiene {book_count} libros asociados."
              f"\tPor favor, elimine o reasigne los libros antes de proseguir. ",'danger') #danger
        return redirect(url_for('book.index'))
    else:     
        category.delete()
        flash("Succesfully Removed","success")
    return redirect(url_for('category.index'))

views/category_view.py
from flask import render_template

def list(categories):
    return render_template('categories/index.html', categories =categories)

def create(form): #sending form for wtforms
    return render_template('categories/create.html', form=form)

def edit(form, category):
    return render_template('categories/edit.html', form=form, category=category)

#optional
def list_active(categories_active):
    return render_template('categories/page.html', categories_active =categories_active)

templates/categories/create.html
{% extends 'base.html' %}
{% block title %} CATEGORY | CREATE {% endblock %}
{% block content %} 
<!--only admin-->

<div class="container">
<h1 class="main-title-banner text-center">Nueva Categoria</h1>

<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('category.create')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.description.label(class="form-label") }}
                {{ form.description(class="form-control")}}
                {% if form.description.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.description.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_active(class="form-check-input", id="is_active_check") }}
                <label class="form-check-label ms-2" for="is_active_check">{{ form.is_active.label }}</label>
                {% if form.is_active.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_active.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/categories/edit.html
{% extends 'base.html' %}
{% block title %} CATEGORY| UPDATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->
<h1 class="main-title-banner text-center">Editar Categoria</h1>
<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('category.edit', id = category.id)}}" method="post" novalidate>  <!--category.id representa el registro enviado basado en el id-->
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.description.label(class="form-label") }}
                {{ form.description(class="form-control")}}
                {% if form.description.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.description.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_active(class="form-check-input", id="is_active_check") }}
                <label class="form-check-label ms-2" for="is_active_check">{{ form.is_active.label }}</label>
                {% if form.is_active.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_active.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/categories/index.html
{% extends 'base.html' %}
{% block title %} CATEGORIES {% endblock %}
{% block content %} 
<div class="container mb-5">
<h1 class="main-title-banner text-center">Lista de Categorias</h1>

<a href="{{url_for('category.create')}}" class="btn btn-success my-3">Añadir Nueva Categoria</a>
<div class="table-card-container ">
<div class="table mt-2 table-responsive">
    <table class="table table-hover table-striped custom-table ">
        <thead class="custom-table-header">
            <tr>
                <th>ID</th><th>CATEGORIA</th><th>DESCRIPCION</th><th>ACTIVO?</th><th colspan="2" class="text-center">ACCIONES</th>
            </tr>
        </thead>
        <tbody>
            {% for item in categories %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.description}}</td>
                    <td>{% if item.is_active %}
                            <p class="text-primary">SI</p>
                        {%else%}
                            <p class="text-danger">NO</p>
                        {% endif %}
                    </td>
                    <td><a href="{{url_for('category.edit',id=item.id)}}" class="btn btn-sm  btn-primary custom-action-btn">Editar</a></td>
                    <td><a href="{{url_for('category.delete',id=item.id)}}" class="btn btn-sm btn-danger custom-action-btn" onclick="return(confirm('Desea eliminar esta Categoria?'))">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
{% endblock %}