controllers/state_controller.py
from flask import redirect, flash, request, url_for, Blueprint
from flask_login import login_required, current_user
from decorators import admin_required
from logmanagerconfig import login_manager

from models.user_model import User
from models.book_model import Book

from models.state_model  import State
from views import state_view
from forms.form_states import CreateForm, EditForm

from database import db

state_bp = Blueprint('state', __name__, url_prefix='/states')

#login_manager
@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(user_id) 

@state_bp.route("/")
#@admin_required
def index():
    states = State.get_all()
    return state_view.list(states=states)

@state_bp.route("/admin/create", methods=['POST','GET'])
@admin_required #if not flash + redirect to run.index 
def create():
    form = CreateForm()
    
    if 'cancel' in request.form:
            return redirect(url_for('state.index'))
        
    if form.validate_on_submit():
        name =  form.name.data
        description = form.description.data
        
        state = State(name, description)
        try:
            state.save() # commit the creation
            flash("Successfully Added","success")
            return redirect(url_for('state.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot Create, Error:{e}", "danger")
    return state_view.create(form=form)
         
@state_bp.route("/admin/edit/<int:id>", methods= ['POST','GET'])
@admin_required
def edit(id):
    state = State.get_by_id(id)
    form = EditForm(obj=state)
    
    if 'cancel' in request.form:
            return redirect(url_for('state.index'))
        
    if form.validate_on_submit():
        form.populate_obj(state)        
        try:
            db.session.commit()
            flash("Succesfully Updated", "success")
            return redirect(url_for('state.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot update, Error:{e}", "danger")
    return state_view.edit(form=form, state=state)

@state_bp.route("/admin/delete/<int:id>", methods=['POST','GET'])
@admin_required
def delete(id):
    state = State.get_by_id(id)
    book_count = Book.get_by_state_id_count(id)
    if book_count > 0 :
        flash(f"No se puede eliminar el estado '{state.name}' porque tiene {book_count} libros asociados."
              f"\tPor favor, elimine o reasigne los libros antes de proseguir. ",'danger') #danger
        return redirect(url_for('book.index'))
    else:
        state.delete()
        flash("Succesfully Removed","success")
        return redirect(url_for('state.index'))

views/state_view.py
from flask import render_template

def list(states):
    return render_template('states/index.html', states =states)

def create(form): #sending form for wtforms
    return render_template('states/create.html', form=form)

def edit(form, state):
    return render_template('states/edit.html', form=form, state=state)

templates/states/create.html
{% extends 'base.html' %}
{% block title %} STATES | CREATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->

<h1 class="main-title-banner text-center">Nuevo Estado de Uso</h1>
<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('state.create')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.description.label(class="form-label") }}
                {{ form.description(class="form-control")}}
                {% if form.description.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.description.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/states/edit.html
{% extends 'base.html' %}
{% block title %} STATES | UPDATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->
<h1 class="main-title-banner text-center">Editar Estado de Libro</h1>

<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('state.edit', id = state.id)}}" method="post" novalidate>  <!--category.id representa el registro enviado basado en el id-->
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.description.label(class="form-label") }}
                {{ form.description(class="form-control")}}
                {% if form.description.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.description.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/states/index.html
{% extends 'base.html' %}
{% block title %} BOOK STATES {% endblock %}
{% block content %} 
<div class="container mb-5">
<h1 class="main-title-banner text-center">Estados Uso de Libro</h1>

<a href="{{url_for('state.create')}}" class="btn btn-success my-3">Añadir Nuevo Estado de Uso</a>
<div class="table-card-container">
<div class="table mt-2 table-responsive">
    <table class="table table-hover table-striped custom-table">
        <thead class="custom-table-header">
            <tr>
                <th>ID</th><th>ESTADO DE USO</th><th>DESCRIPCION</th><th colspan="2" class="text-center">ACCIONES</th>
            </tr>
        </thead>
        <tbody>
            {% for item in states %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.description}}</td>
                    <td><a href="{{url_for('state.edit',id=item.id)}}" class="btn btn-sm btn-primary custom-action-btn">Editar</a></td>
                    <td><a href="{{url_for('state.delete',id=item.id)}}" class="btn btn-sm btn-danger custom-action-btn" onclick="return(confirm('Desea eliminar este Estado de Libro?'))">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
{% endblock %}