controllers/user_controller.py
from flask import redirect, flash, request, url_for, Blueprint
from flask_login import login_required, login_user, logout_user, current_user
from decorators import admin_required
from logmanagerconfig import login_manager

from models.user_model import User
from models.order_model import Order

from views import user_view

from forms.form_users import CreateForm, LoginForm, EditForm

from database import db

user_bp = Blueprint('user', __name__, url_prefix='/users')

#login manager
@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(user_id) 

@user_bp.route("/")
@admin_required
def index():
    users = User.get_all()
    return user_view.list(users=users)

@user_bp.route("/admin/create", methods=['POST','GET'])
@admin_required #if not flash + redirect to "/"
def create():
    form = CreateForm()
   
    if 'cancel' in request.form:
        return redirect(url_for('user.index'))
    
    if form.validate_on_submit():

        name =  form.name.data
        username = form.username.data
        passwd = form.passwd.data
        is_admin = form.is_admin.data
        email = form.email.data
        phone = form.phone.data
        
        user = User(name,username, passwd, is_admin,email,phone)
        try:
            user.save()
            flash("Successfully Added, please log in","success")
            return redirect(url_for('user.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot Create, Error:{e}", "danger")
    return user_view.create(form=form)
         
@user_bp.route("/admin/edit/<int:id>", methods= ['POST','GET'])
@admin_required
def edit(id):
    user = User.get_by_id(id)
    form = EditForm(obj=user)
    
    if 'cancel' in request.form:
        return redirect(url_for('user.index'))
    
    if form.validate_on_submit() or request.method == 'POST':
        if form.cancel.data:
            return redirect(url_for('user.index'))
        form.populate_obj(user)        
        # isolated process for password
        passwd = request.form.get('passwd')
        user.update_pass(passwd=passwd)
        try:
            db.session.commit()
            flash("Succesfully Updated", "success")
            return redirect(url_for('user.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot update, Error:{e}", "danger")
    return user_view.edit(form=form, user=user)

@user_bp.route("/admin/delete/<int:id>", methods=['POST','GET'])
@admin_required
def delete(id):
    user = User.get_by_id(id)
    orders_count = Order.get_by_user_id_count(id)
    if orders_count > 0:
        flash(f"No se puede eliminar el usuario '{user.username}'({user.name}) porque tiene {orders_count} pedidos asociados."
                f"\tPor favor, elimine o reasigne los pedidos antes de proseguir. ",'danger') #danger
        return redirect(url_for('order.index'))
    user.delete()
    flash("Succesfully Removed","success")
    return redirect(url_for('user.index'))

@user_bp.route("/signup", methods=['POST','GET'])
def signup():
    if current_user.is_authenticated:
        flash('You are already in, you cannot signup',"warning")
        return redirect(url_for('index'))
    form = CreateForm()
   
    if 'cancel' in request.form:
        return redirect(url_for('index'))
    
    if form.validate_on_submit():
        name = form.name.data
        username = form.username.data
        passwd = form.passwd.data
        email = form.email.data
        phone = form.phone.data
        
        user = User(name=name,username=username,passwd=passwd,is_admin=False,email=email,phone=phone)
        try:
            user.save()
            flash("Succesfully Registered, please Log in", "success")
            return redirect(url_for('index'))
        except Exception as e:
            db.session.rollback()
            flash(f'Cannot Sign Up, an Error was detected: {e}',"danger")
    return user_view.signup(form=form)

@user_bp.route("/login",methods=['POST','GET'])
def login():
    if current_user.is_authenticated:
        flash('You are already logged in',"warning")
        return redirect(url_for('index'))
    form = LoginForm()
    
    if 'cancel' in request.form:
        return redirect(url_for('index'))
    
    if form.validate_on_submit():
        
        user = User.get_by_username(form.username.data)
        if user and user.verify_passwd(form.passwd.data):
            login_user(user)
            flash("Succesfully Logged","success")
            return redirect(url_for('index'))
        else:
            flash("User or Password not valid !","danger")
    return user_view.login(form=form)

@user_bp.route("/logout",methods=['POST','GET'])
@login_required
def logout():
    logout_user()
    flash("Successfully Logged Out","warning")
    return redirect(url_for('index'))

views/user_view.py
from flask import render_template

def list(users):
    return render_template('users/index.html', users =users)

def create(form): #sending form for wtforms
    return render_template('users/create.html', form=form)

def edit(form, user):
    return render_template('users/edit.html', form=form, user=user)

def signup(form): #sending form for wtforms
    return render_template('users/signup.html', form=form)

def login(form):
    return render_template('users/login.html', form = form)
#it could be necessary to add customized-list showing methods

templates/users/create.html
{% extends 'base.html' %}
{% block title %} USERS | CREATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->
<h1 class="main-title-banner text-center">Nuevo Usuario</h1>
<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('user.create')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control")}}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.passwd.label(class="form-label") }}
                {{ form.passwd(class="form-control", placeholder="Escriba su Contraseña")}}
                {% if form.passwd.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.passwd.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control")}}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.email.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.phone.label(class="form-label") }}
                {{ form.phone(class="form-control")}}
                {% if form.phone.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.phone.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_admin(class="form-check-input", id="is_admin_check") }}
                <label class="form-check-label ms-2" for="is_admin_check">{{ form.is_admin.label }}</label>
                {% if form.is_admin.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_admin.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>

        </form>
    </div>
</div>        
</div>
{% endblock %}

templates/users/edit.html
{% extends 'base.html' %}
{% block title %} USERS | UPDATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->

<h1 class="main-title-banner text-center">Editar Usuario</h1>

 <div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">

        <form action="{{url_for('user.edit', id = user.id)}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control")}}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Contrasena</label>
                <input type="password" class="form-control" placeholder="Nueva Constraseña" name="passwd">
            </div>
            
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control")}}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.email.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.phone.label(class="form-label") }}
                {{ form.phone(class="form-control")}}
                {% if form.phone.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.phone.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_admin(class="form-check-input", id="is_admin_check") }}
                <label class="form-check-label ms-2" for="is_admin_check">{{ form.is_admin.label }}</label>
                {% if form.is_admin.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_admin.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}
{% block title %} USERS {% endblock %}
{% block content %} 

<div class="container mb-5">
<h1 class="main-title-banner text-center">Usuarios Registrados</h1>


<a href="{{url_for('user.create')}}" class="btn btn-success mb-3">Añadir Nuevo Usuario</a>
<div class="table-card-container">
<div class="table mt-2 table-responsive">
    <table class="table table-hover table-striped custom-table">
        <thead class="custom-table-header">
            <tr>
                <th>ID</th><th>NOMBRE</th><th>USERNAME</th><th>CORREO</th><th>TELEFONO</th><th>ES ADMIN?</th> <th>CREACION</th> <th colspan="2" class="text-center">ACCIONES</th>
            </tr>
        </thead>
        <tbody>
            {% for item in users %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.username}}</td>
                    <td>{{item.email}}</td>
                    <td>{{item.phone}}</td>
                    <td>{% if item.is_admin %}
                            <p class="text-primary">SI</p>
                        {%else%}
                            <p class="text-danger">NO</p>
                        {% endif %}
                    </td>
                    <td>{{item.created_at.strftime('%d/%m/%Y')}}</td>
                    <td><a href="{{url_for('user.edit',id=item.id)}}" 
                        class="btn btn-sm btn-primary {% if current_user.username == item.username %} disabled {% endif %}  custom-action-btn"> Editar </a></td>
                    <td><a href="{{url_for('user.delete',id=item.id)}}" 
                        class="btn btn-sm btn-danger {% if current_user.username == item.username %} disabled {% endif %}  custom-action-btn" onclick="return(confirm('Desea eliminar este Usuario?'))">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
</div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% block title %} USERS | LOGIN {% endblock %}
{% block content %} 
<div class="container">
<!-- all users -->
<h1 class="main-title-banner text-center">Iniciar Sesion</h1>

<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
       
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('user.login')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control")}}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ form.passwd.label(class="form-label") }}
                {{ form.passwd(class="form-control")}}
                {% if form.passwd.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.passwd.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="my-3  d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
            {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>    
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% block title %} USERS | SIGNUP {% endblock %}
{% block content %} 
<div class="container">
<!-- all users -->
<h1 class="main-title-banner text-center">Registrar Usuario</h1>
<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('user.signup')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(class="form-control")}}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.passwd.label(class="form-label") }}
                {{ form.passwd(class="form-control", placeholder="Escriba su Contraseña")}}
                {% if form.passwd.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.passwd.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control")}}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.email.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.phone.label(class="form-label") }}
                {{ form.phone(class="form-control")}}
                {% if form.phone.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.phone.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}