controllers/provider_controller.py
from concurrent.futures.thread import _python_exit
from flask import redirect, flash, request, url_for, Blueprint
from flask_login import login_required, current_user
from decorators import admin_required
from logmanagerconfig import login_manager

from models.user_model import User
from models.purchase_model import Purchase

from models.provider_model  import Provider
from views import provider_view
from forms.form_providers import CreateForm, EditForm

from database import db

provider_bp = Blueprint('provider', __name__, url_prefix='/providers')

#login_manager
@login_manager.user_loader
def load_user(user_id):
    return User.get_by_id(user_id) 

@provider_bp.route("/")
#@admin_required
def index():
    providers = Provider.get_all()
    return provider_view.list(providers=providers)

@provider_bp.route("/admin/create", methods=['POST','GET'])
@admin_required #if not flash + redirect to run.index 
def create():
    form = CreateForm()
    
    if 'cancel' in request.form:
        return redirect(url_for('provider.index'))
    
    if form.validate_on_submit():
        name =  form.name.data
        email = form.email.data
        phone = form.phone.data
        address = form.address.data
        is_active = form.is_active.data
        
        provider = Provider(name,email,phone,address, is_active)
        try:
            provider.save() # commit the creation
            flash("Successfully Added","success")
            return redirect(url_for('provider.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot Create, Error:{e}", "danger")
    return provider_view.create(form=form)
         
@provider_bp.route("/admin/edit/<int:id>", methods= ['POST','GET'])
@admin_required
def edit(id):
    provider = Provider.get_by_id(id)
    form = EditForm(obj=provider) # populate form fields with same name object fields
    
    if 'cancel' in request.form:
        return redirect(url_for('provider.index'))
    
    if form.validate_on_submit():
        form.populate_obj(provider)       #store changes 
        try:
            db.session.commit() #commit changes in DB
            flash("Succesfully Updated", "success")
            return redirect(url_for('provider.index'))
        except Exception as e:
            db.session.rollback()
            flash(f"Cannot update, Error:{e}", "danger")
    return provider_view.edit(form=form, provider=provider)

@provider_bp.route("/admin/delete/<int:id>", methods=['POST','GET'])
@admin_required
def delete(id):
    provider = Provider.get_by_id(id)
    purchase_count = Purchase.get_by_provider_id_count(provider.id)
    
    if purchase_count > 0:
        flash(f"No se puede eliminar el proveedor '{provider.name}' porque tiene {purchase_count} compras asociadas."
              f"\tPor favor, elimine o reasigne las compras antes de proseguir. ",'danger') #danger
        return redirect(url_for('purchase.index'))
    else:
        provider.delete()
        flash("Succesfully Removed","success")
        return redirect(url_for('provider.index'))

views/provider_view.py
from flask import render_template

def list(providers):
    return render_template('providers/index.html', providers =providers)

def create(form): #sending form for wtforms
    return render_template('providers/create.html', form=form)

def edit(form, provider):
    return render_template('providers/edit.html', form=form, provider=provider)

#optional
def list_active(providers_active):
    return render_template('providers/page.html', providers_active =providers_active)

templates/providers/create.html
{% extends 'base.html' %}
{% block title %} PROVIDER | CREATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->
<h1 class="main-title-banner text-center">Nuevo Proveedor</h1>

 <div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('provider.create')}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control")}}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.email.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.phone.label(class="form-label") }}
                {{ form.phone(class="form-control")}}
                {% if form.phone.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.phone.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ form.address.label(class="form-label") }}
                {{ form.address(class="form-control")}}
                {% if form.address.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.address.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_active(class="form-check-input", id="is_active_check") }}
                <label class="form-check-label ms-2" for="is_active_check">{{ form.is_active.label }}</label>
                {% if form.is_active.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_active.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/providers/edit.html
{% extends 'base.html' %}
{% block title %} PROVIDER | UPDATE {% endblock %}
{% block content %} 
<div class="container">
<!--only admin-->
<h1 class="main-title-banner text-center">Editar Proveedor</h1>

<div class="row justify-content-center"> {# Usa 'row' y 'justify-content-center' para centrar el contenido #}
        {# Define el ancho de la columna en diferentes tamaños de pantalla #}
    <div class="col-md-8 col-lg-6 form-panel-card">
        <form action="{{url_for('provider.edit',id = provider.id)}}" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {{ form.name(class="form-control")}}
                {% if form.name.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.name.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control")}}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.email.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.phone.label(class="form-label") }}
                {{ form.phone(class="form-control")}}
                {% if form.phone.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.phone.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3">
                {{ form.address.label(class="form-label") }}
                {{ form.address(class="form-control")}}
                {% if form.address.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.address.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="mb-3 form-check d-flex align-items-center"> <!--tambien puede sr end-->
                {{ form.is_active(class="form-check-input" , id="is_active_check") }}
                <label class="form-check-label ms-2" for="is_active_check">{{ form.is_active.label }}</label>
                {% if form.is_active.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.is_active.errors %}
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="my-3 d-flex justify-content-center">
                {{ form.submit(class="btn btn-primary")}}
                <span class="mx-3"></span>
                {{ form.cancel(class="btn btn-danger")}}
            </div>
            
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/providers/index.html
{% extends 'base.html' %}
{% block title %} PROVEEDORES {% endblock %}
{% block content %} 
<div class="container mb-5">
<h1 class="main-title-banner text-center">Lista de Proveedores</h1>
<a href="{{url_for('provider.create')}}" class="btn btn-success my-3">Añadir Nuevo Proveedor</a>
<div class="table-card-container">
<div class="table mt-2 table-responsive">
    <table class="table table-hover table-striped custom-table">
        <thead class="custom-table-header">
            <tr>
                <th>ID</th><th>NOMBRE</th><th>EMAIL</th><th>TELEFONO</th><th>DIRECCION </th><th>ACTIVO?</th> <th colspan="2" class="text-center">ACCIONES</th>
            </tr>
        </thead>
        <tbody>
            {% for item in providers %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.email}}</td>
                    <td>{{item.phone}}</td>
                    <td>{{item.address}}</td>
                    <td>{% if item.is_active %}
                            <p class="text-primary">SI</p>
                        {%else%}
                            <p class="text-danger">NO</p>
                        {% endif %}
                    </td>
                    <td><a href="{{url_for('provider.edit',id=item.id)}}" class="btn btn-sm btn-primary custom-action-btn">Editar</a></td>
                    <td><a href="{{url_for('provider.delete',id=item.id)}}" class="btn btn-sm btn-danger custom-action-btn" onclick="return(confirm('Desea eliminar este Proveedor?'))">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
</div>
</div>
{% endblock %}